#ifndef Executor
#define Executor
#include <stdio.h>

//mtakes a random value and returns a value between 50(inclusive) and 100(exclusive)
int get_iteration_no(int rand);

// This function takes in a random value generated by rand()
// and returns a value between 100 (inclusive) and 150 (exclusive)
int get_arr_size(int rand);

// This function takes in a random value generated by rand()
// and generates a value between 65 (inclusive) and 90 (inclusive), which is then explicitly
// converted into a character and returned to the calling function. 
char get_arr_val(int rand);

// This function takes the
// populated array, it’s size and the address to maxCount variable used in get_running_ratio().
// It then counts the number of vowels and consonants, and returns the ratio of vowels/consonants.
float ratio(char *arr, int size, int *maxCountPointer);

// the bad boy that does it all.
double get_running_ratio(); 

#endif